# This file was generated by GoReleaser. DO NOT EDIT.
class Cjwt < Formula
  desc "tool for inspecting jwts"
  homepage "https://github.com/aricart/cjwt"
  version "1.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aricart/cjwt/releases/download/v1.0.4/cjwt-darwin-amd64.zip"
    sha256 "49da03d953855db54303c5e84debc82b87859ff9de6903b544c18facd5057fe1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aricart/cjwt/releases/download/v1.0.4/cjwt-linux-amd64.zip"
      sha256 "412ec376a167ee7cbe1ddf29a4fa6afb38b5bc32b6e8e13c47573b3740925daf"
    end
  end

  def install
    bin.install "cjwt"
  end

  test do
    system "#{bin}/cjwt --help"
  end
end
