# This file was generated by GoReleaser. DO NOT EDIT.
class Cjwt < Formula
  desc "tool for inspecting jwts"
  homepage "https://github.com/aricart/cjwt"
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aricart/cjwt/releases/download/v1.0.6/cjwt-darwin-amd64.zip"
    sha256 "a58cf282e35f4933be52651d595c55758a1eb74772b7fe97c94c1a499d871c03"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aricart/cjwt/releases/download/v1.0.6/cjwt-linux-amd64.zip"
      sha256 "7ddc94767dcb4489c01b7bf99684c4fce17a73d5519a743bf53f383eb0cf1607"
    end
  end

  def install
    bin.install "cjwt"
  end

  test do
    system "#{bin}/cjwt --help"
  end
end
