# This file was generated by GoReleaser. DO NOT EDIT.
class GoTemplate < Formula
  desc "go-template description"
  homepage "https://github.com/aricart/go-template"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aricart/go-template/releases/download/v0.0.2/go-template-darwin-amd64.zip"
    sha256 "70f1f2c9c97e84bea2873949970aee1e8db7bd291453e6fca1ce551417661c58"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/aricart/go-template/releases/download/v0.0.2/go-template-linux-amd64.zip"
      sha256 "407fc8eaa2385064886364a51da09a1c57c6a91d5c8832f49f84833d69bab9bf"
    end
  end

  def install
    bin.install "go-template"
  end

  test do
    system "#{bin}/go-template --help"
  end
end
